# Generated by Django 2.1.2 on 2020-01-20 13:17

import Venter.helpers
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Venter', '0048_file_wordcloud_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=Venter.helpers.get_user_profile_picture_path)),
                ('phone_number', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Please enter a valid phone number', regex='^[6-9]\\d{9}$')])),
                ('organisation_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Venter.Organisation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('london', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=Venter.helpers.get_user_profile_picture_path),
        ),
    ]
